config/routes.rb
MusicianNetwork::Application.routes.draw do

  resources :musicians
  resources :songs

end

app/models/musicans_song.rb
# musicians_songs.rb
class MusiciansSong < ActiveRecord::Base
  belongs_to :musician
  belongs_to :song 
end

app/models/musician.rb
# musician.rb

class Musician < ActiveRecord::Base
  has_many :musician_songs  #define this first
  has_many :songs, :through => :musician_songs  #then you can use musicians_songs here
end

app/models/musician_song.rb
# musicians_songs.rb
class MusicianSong < ActiveRecord::Base
  belongs_to :musician
  belongs_to :song 
end

app/models/song.rb
# song.rb

class Song < ActiveRecord::Base
  has_many :musician_songs
  has_many :musicians, :through => :musician_songs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/musicians_controller.rb
class MusiciansController < ApplicationController

  def index
    @musicians = Musician.all
  end

  def show
    @musician = Musician.find(params[:id])
  end

  def new 
    @musician = Musician.new
  end

  def edit
    @musician = Musician.find(params[:id])
  end

  #POST to create
  def create
    @musician = Musician.new(params[:musician])
    if @musician.save
      redirect_to @musician, notice: 'Musician profile was succesfully created'
    else 
      render action: "new"
    end
  end

  def update
    @musician = Musician.find(params[:id])
    if @musician.update_attributes(params[:musician])
      redirect_to @musician, notice: 'Musician profile was succesfully updated'
    else
      render action: "edit"
    end
  end

  def destroy
    @musician = Musician.find(params[:id])
    @musician.destroy

    redirect_to musicians_path
  end

end

app/controllers/songs_controller.rb
class SongsController < ApplicationController

  def index
    @songs = Song.all
  end

  def show
    @song = Song.find(params[:id])
  end

  def new
    @song = Song.new
  end

  def create
    @song = Song.new(params[:song])
    if @song.save
      redirect_to @song
    else
      render "new"
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/musicians_helper.rb
module MusiciansHelper
end

app/helpers/song_helper.rb
module SongHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MusicianNetwork</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/musicians/_form.html.haml
=form_for(@musician) do |f|
	.field 
		= f.label :first
		= f.text_field :first

	.field 
		= f.label :last
		= f.text_field :last

	.field
		= f.label :instrument
		= f.select :instrument, ["Guitar", "Saxophone", "Electric Bass", "Keyboard", "Triangle"]

	.actions
		= f.submit 

app/views/musicians/index.html.haml
%h1 Musicians

%table
	%tr
		%th First Name  
		%th Last Name  
		%th Instrument  
		%th Learned Songs  

	- @musicians.each do |musician|
		%tr
			%td= musician.first
			%td= musician.last
			%td= musician.instrument
			%td
				%ul
					- musician.songs.each do |song|
						%li= link_to song.artist + ' - ' + song.title, song
			%td= link_to 'Show', musician
			%td= link_to 'Edit', edit_musician_path(musician)
			%td= link_to 'Destroy', musician, confirm: "Are you sure?", method: :delete
%br
=link_to 'New Musician Profile', new_musician_path

app/views/musicians/new.html.haml
%h1 Create Musician Profile

= render 'form' 

app/views/musicians/show.html.haml
%h1 Musician
%h3= "Name: " + @musician.first + " " + @musician.last
%h3= "Instrument: " + @musician.instrument
%h3 Learned Songs:
%ul
	-@musician.songs.each do |song|
		%li=song.artist + " - " + song.title + " (#{song.genre})"

= link_to 'Musicians Index', musicians_path

app/views/songs/_form.html.haml
=form_for(@song) do |f|
	.field 
		= f.label :title
		= f.text_field :title

	.field 
		= f.label :artist
		= f.text_field :artist

	.field
		= f.label :genre
		= f.select :genre, ["Rock", "Funk", "Raggae", "Jazz", "Hip-hop"]

	.actions
		= f.submit 

app/views/songs/edit.html.haml
%h1
=render 'form'

app/views/songs/index.html.haml
%h1 Songs

%table
	%tr
		%th Title
		%th Artist  
		%th Genre  
		%th Musician Learn Count  

	- @songs.each do |song|
		%tr
			%td= song.title
			%td= song.artist
			%td= song.genre
			%td= song.musicians.count
			%td= link_to 'Show', song
			%td= link_to 'Edit', edit_song_path(song)
			%td= link_to 'Destroy', song, confirm: "Are you sure?", method: :delete
%br
=link_to 'New Song', new_song_path

app/views/songs/new.html.haml
%h1 Create Song Profile

= render 'form' 

app/views/songs/show.html.haml
%h1 Song
%h3= "Title: " + @song.title 
%h3= "Artist: " + @song.artist
%h3= "Genre: " + @song.genre
%h3 Artists that know this song:
%ul
	-@song.musicians.each do |musician|
		%li=musician.first + " " +  musician.last 
		%p= link_to('Profile', musician)

= link_to 'Songs Index', songs_path